version: "3.8"

services:
  galera1:
    image: bitnami/mariadb-galera:latest
    container_name: galera1
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=galerapass
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
      - MARIADB_DATABASE=mydb
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_ENABLE=true
      - MARIADB_GALERA_MARIABACKUP_USER=backup
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backuppass
      - MARIADB_ROOT_HOST=%
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes

    volumes:
      - galera1_data:/bitnami/mariadb
    ports:
      - "3306:3306"
    networks:
      - galera-net

  galera2:
    image: bitnami/mariadb-galera:latest
    container_name: galera2
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=galerapass
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
      - MARIADB_DATABASE=mydb
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera1,galera2,galera3
      - MARIADB_GALERA_ENABLE=true
      - MARIADB_GALERA_MARIABACKUP_USER=backup
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backuppass
      - MARIADB_ROOT_HOST=%
    volumes:
      - galera2_data:/bitnami/mariadb
    ports:
      - "3307:3306"
    depends_on:
      - galera1
    networks:
      - galera-net

  galera3:
    image: bitnami/mariadb-galera:latest
    container_name: galera3
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=galerapass
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
      - MARIADB_DATABASE=mydb
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera1,galera2,galera3
      - MARIADB_GALERA_ENABLE=true
      - MARIADB_GALERA_MARIABACKUP_USER=backup
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backuppass
      - MARIADB_ROOT_HOST=%
    volumes:
      - galera3_data:/bitnami/mariadb
    ports:
      - "3308:3306"
    depends_on:
      - galera1
    networks:
      - galera-net

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - galera-net

volumes:
  galera1_data:
    name: galera1_data
  galera2_data:
    name: galera2_data
  galera3_data:
    name: galera3_data

networks:
  galera-net:
    driver: bridge
